// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6O-XRdV-bxtInXLmQPSGzAlLF01WW9I',
    appId: '1:766808964045:web:a0e7d1e44180951c786284',
    messagingSenderId: '766808964045',
    projectId: 'vizitom-f3d2f',
    authDomain: 'vizitom-f3d2f.firebaseapp.com',
    storageBucket: 'vizitom-f3d2f.firebasestorage.app',
    measurementId: 'G-N6SBF68SPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZobF3_hdaRM85A03voR32_Cux39SzWrg',
    appId: '1:766808964045:android:1292beabaedd1bc2786284',
    messagingSenderId: '766808964045',
    projectId: 'vizitom-f3d2f',
    storageBucket: 'vizitom-f3d2f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5T3LexZcg8iGZfNoVw9Y7Jp8N9rCRSAw',
    appId: '1:766808964045:ios:8e4c0a741ca66147786284',
    messagingSenderId: '766808964045',
    projectId: 'vizitom-f3d2f',
    storageBucket: 'vizitom-f3d2f.firebasestorage.app',
    iosBundleId: 'com.example.provider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6O-XRdV-bxtInXLmQPSGzAlLF01WW9I',
    appId: '1:766808964045:web:41e7a6e25b1b8384786284',
    messagingSenderId: '766808964045',
    projectId: 'vizitom-f3d2f',
    authDomain: 'vizitom-f3d2f.firebaseapp.com',
    storageBucket: 'vizitom-f3d2f.firebasestorage.app',
    measurementId: 'G-LTR90MFM4C',
  );
}
